/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface ExperienceItem {
  company: string;
  role: string;
  period: string;
  description: string;
  location?: string;
}

export interface Skill {
  name: string;
  category: 'SEO' | 'Content' | 'Strategy' | 'Design' | 'Technical';
}

export const EXPERIENCES: ExperienceItem[] = [
  {
    company: 'Carpe Diem',
    role: 'Team Lead / SEO Strategist',
    period: '2024 - 2026',
    location: 'United Kingdom (Remote)',
    description: 'Leading both SEO and content writing departments. Strategy building, content execution, and UI/UX focused design. QA specialist turned Lead.',
  },
  {
    company: 'Broad Vision',
    role: 'Marketing Copywriter & SEO Specialist',
    period: '2022 - 2024',
    location: 'Germany (Remote)',
    description: 'Managed pure marketing copywriting, on-page/off-page SEO, landing pages, campaign copies, and creative design.',
  },
  {
    company: 'Freelance',
    role: 'Ebook Writer & Video Editor',
    period: '2020 - 2022',
    description: 'Specialized in freelance ebook writing and high-end video editing services.',
  },
  {
    company: 'YouTube Automation',
    role: 'Full-Stack Creator',
    period: '2017 - 2020',
    description: 'Started journey during matriculation. Handled scriptwriting, editing, graphic design, SEO, and social media management.',
  },
];

export const NICHES = [
  'Life & Annuity Insurance', 'Homeowners (High-Value) Protection', 
  'Auto & Mobility SEO', 'Cyber Liability', 'Fintech & SaaS',
  'South Carolina Regional SEO', 'Medical Niche Authority', 
  'Technical Content Architecture'
];

export const SKILLS: Skill[] = [
  { name: 'On-Page SEO Mastery', category: 'SEO' },
  { name: 'High-Competition Keyword Research', category: 'SEO' },
  { name: 'Conversion-Focused Strategy', category: 'Strategy' },
  { name: 'Niche Content Authority', category: 'Content' },
  { name: 'Team Leadership (SEO/Content)', category: 'Strategy' },
  { name: 'Technical SEO Audit', category: 'SEO' },
  { name: 'UI/UX for Content Conversion', category: 'Design' },
  { name: 'Strategic Content QA', category: 'Content' },
];

export const CONTACT_INFO = {
  email: 'fazalsubhaniwriter@gmail.com',
  linkedin: 'https://www.linkedin.com/in/fazal-e-subhani',
  phone: '+923081168623',
};

export interface PortfolioCategory {
  title: string;
  icon: string;
  type: 'on-page' | 'off-page' | 'gmb' | 'web-pages';
  links: { id: string; label: string; url: string }[];
}

export const PORTFOLIO_CATEGORIES: PortfolioCategory[] = [
  // --- ON-PAGE BLOGS (Insurance focus) ---
  {
    title: 'Auto Insurance SC',
    icon: 'Car',
    type: 'on-page',
    links: [
      { id: 'op1', label: 'Greenwood SC Switch Guide', url: 'https://myinsurancecorner.com/why-drivers-are-switching-to-auto-insurance-in-greenwood-sc-and-how-you-can-too/' },
      { id: 'op2', label: 'Advantage Auto Architecture', url: 'https://myinsurancecorner.com/advantage-auto-insurance-a-plan-that-fits-high-mileage-drivers/' },
      { id: 'op3', label: 'SC Premium Factors', url: 'https://myinsurancecorner.com/what-factors-affect-auto-insurance-premiums-in-south-carolina/' },
      { id: 'op4', label: 'Affordable Coverage Guide', url: 'https://myinsurancecorner.com/auto-insurance-greenwood-sc-a-complete-guide-to-affordable-coverage/' },
      { id: 'op5', label: 'SC Requirements Analysis', url: 'https://myinsurancecorner.com/understanding-south-carolinas-car-insurance-requirements/' },
    ],
  },
  {
    title: 'Homeowners Protection',
    icon: 'Home',
    type: 'on-page',
    links: [
      { id: 'op6', label: '90% Homeowners Regret', url: 'https://myinsurancecorner.com/90-of-homeowners-wish-they-had-better-property-insurance-dont-be-one-of-them/' },
      { id: 'op7', label: 'Allstate High-Value Homes', url: 'https://myinsurancecorner.com/allstate-homeowners-insurance-the-best-choice-for-high-value-homes/' },
      { id: 'op8', label: 'Storm Zone Strategy', url: 'https://myinsurancecorner.com/do-you-live-in-a-storm-zone-this-homeowners-insurance-is-made-for-you/' },
      { id: 'op9', label: 'Military Family Benefits', url: 'https://myinsurancecorner.com/best-homeowners-insurance-for-military-families-get-exclusive-benefits/' },
      { id: 'op10', label: 'Smarter Choice Checklist', url: 'https://myinsurancecorner.com/the-smart-homeowners-checklist-how-to-save-on-home-insurance-without-cutting-corners/' },
    ],
  },
  {
    title: 'Life & Annuities',
    icon: 'HeartPulse',
    type: 'on-page',
    links: [
      { id: 'op11', label: 'Smart Retirement Move', url: 'https://myinsurancecorner.com/could-life-annuity-insurance-be-your-smartest-retirement-move/' },
      { id: 'op12', label: '5% Growth Annuity', url: 'https://myinsurancecorner.com/earn-up-to-5-growth-with-an-annuity-with-life-insurance-plan/' },
      { id: 'op13', label: 'The Life Insurance Gap', url: 'https://myinsurancecorner.com/70-of-americans-have-no-life-insurance-are-you-one-of-them/' },
      { id: 'op14', label: 'Senior Life No Medical', url: 'https://myinsurancecorner.com/get-senior-life-insurance-in-less-than-10-minutes-no-medical-exam-needed/' },
      { id: 'op15', label: 'Protective Life Trends', url: 'https://myinsurancecorner.com/lock-in-low-rates-today-protective-life-insurance-prices-are-rising-soon/' },
    ],
  },
  {
    title: 'Cyber & Business',
    icon: 'ShieldAlert',
    type: 'on-page',
    links: [
      { id: 'op16', label: 'Cyber Liability Essential', url: 'https://myinsurancecorner.com/cyber-liability-insurance-essential-protection-for-your-business/' },
      { id: 'op17', label: 'Cyber Cost Analysis', url: 'https://myinsurancecorner.com/cyber-liability-insurance-cost-what-you-need-to-know/' },
      { id: 'op18', label: 'Cyber Threat Defense', url: 'https://myinsurancecorner.com/best-cyber-liability-insurance-protect-your-business-from-cyber-threats/' },
    ],
  },
  {
    title: 'Managed IT & Security',
    icon: 'Server',
    type: 'on-page',
    links: [
      { id: 'op26', label: 'ROI of Managed Firewall', url: 'https://turnkey.pro/the-roi-of-investing-in-managed-firewall-and-endpoint-protection-in-the-chicago-suburbs/' },
      { id: 'op27', label: 'Cloud Security for SMBs', url: 'https://turnkey.pro/how-cloud-security-solutions-can-secure-your-wheeling-small-business-data/' },
      { id: 'op28', label: 'Essential IT Practices', url: 'https://turnkey.pro/essential-it-security-practices-for-wheeling-startups-and-small-businesses/' },
      { id: 'op29', label: 'Multi-layered Cybersecurity', url: 'https://turnkey.pro/why-multi-layered-cybersecurity-matters-for-suburban-chicago-companies/' },
      { id: 'op30', label: 'Compliance for Chicago SMBs', url: 'https://turnkey.pro/cybersecurity-compliance-requirements-for-chicago-area-small-businesses/' },
      { id: 'op31', label: 'SD-WAN Benefits', url: 'https://turnkey.pro/how-wheeling-businesses-can-benefit-from-sd-wan-networking-solutions/' },
      { id: 'op32', label: 'Downtime vs Investment', url: 'https://turnkey.pro/the-cost-of-downtime-vs-emergency-it-support-investment/' },
      { id: 'op33', label: 'WFH IT Support', url: 'https://turnkey.pro/the-role-of-managed-it-services-in-supporting-work-from-home-employees-in-the-chicago-area/' },
      { id: 'op34', label: 'Emergency IT Warning Signs', url: 'https://turnkey.pro/five-signs-you-need-emergency-it-support-for-your-wheeling-based-business/' },
      { id: 'op35', label: 'Team Diversity in IT', url: 'https://turnkey.pro/why-diversity-in-it-support-teams-enhances-cybersecurity-in-northern-suburbs-companies/' },
      { id: 'op36', label: 'HIPAA & PCI Compliance', url: 'https://turnkey.pro/how-it-compliance-helps-wheeling-companies-achieve-hipaa-and-pci/' },
      { id: 'op37', label: 'Cyberattack Preparedness', url: 'https://turnkey.pro/is-your-wheeling-business-prepared-for-a-cyberattack/' },
      { id: 'op38', label: 'Local Success Stories', url: 'https://turnkey.pro/local-spotlight-success-stories-of-chicago-suburban-businesses-partnering-with-turnkey-it/' },
      { id: 'op39', label: 'Cyber Hygiene Training', url: 'https://turnkey.pro/how-cyber-hygiene-training-can-protect-your-employees-and-business-in-the-chicago-suburbs/' },
      { id: 'op40', label: 'SLA for Emergency IT', url: 'https://turnkey.pro/what-makes-a-great-sla-for-emergency-it-services-insights-for-chicago-area-smbs/' },
      { id: 'op41', label: 'Cloud vs On-Premises', url: 'https://turnkey.pro/expert-tips-on-choosing-between-cloud-vs-on-premises-it-security-solutions-in-northern-illinois/' },
      { id: 'op42', label: 'Handling Client Data Safely', url: 'https://turnkey.pro/how-can-you-avoid-malicious-code-when-handling-client-data/' },
      { id: 'op43', label: 'Rapid Recovery Plans', url: 'https://turnkey.pro/incident-response-plan-the-role-of-managed-it-services-in-rapid-recovery/' },
      { id: 'op44', label: 'AI in Cybersecurity', url: 'https://turnkey.pro/the-impact-of-ai-in-cybersecurity-on-data-compliance-and-privacy/' },
      { id: 'op45', label: 'Small Business IT Costs', url: 'https://turnkey.pro/how-much-is-it-support-really-costing-your-wheeling-small-business/' },
      { id: 'op46', label: 'Microsoft 365 vs Google', url: 'https://turnkey.pro/microsoft-365-vs-google-workspace-which-is-better-for-small-businesses-in-the-chicago-suburbs/' },
      { id: 'op47', label: 'Network Security Audit', url: 'https://turnkey.pro/why-every-small-business-in-wheeling-needs-a-network-security-audit-in-2026/' },
      { id: 'op48', label: 'Office Move IT Checklist', url: 'https://turnkey.pro/the-small-business-owners-it-checklist-before-moving-to-a-new-office-in-northern-illinois/' },
      { id: 'op49', label: 'Outgrown IT Setup Signs', url: 'https://turnkey.pro/5-signs-your-chicago-area-small-business-has-outgrown-its-current-it-setup/' },
      { id: 'op50', label: 'Sophos MDR Explained', url: 'https://turnkey.pro/sophos-mdr-explained-the-new-standard-for-small-business-cybersecurity/' },
      { id: 'op51', label: 'Manufacturing Operational Risk', url: 'https://turnkey.pro/how-wheeling-manufacturers-can-reduce-operational-risk-with-managed-it-services/' },
      { id: 'op52', label: 'Cloud Migration Strategy', url: 'https://turnkey.pro/cloud-migration-checklist-for-small-businesses-in-the-chicago-suburbs/' },
      { id: 'op53', label: 'Data Loss Consequences', url: 'https://turnkey.pro/what-happens-to-your-business-data-if-your-server-dies-tonight/' },
      { id: 'op54', label: 'Insider IT Threats', url: 'https://turnkey.pro/how-to-protect-your-wheeling-business-from-insider-it-threats/' },
      { id: 'op55', label: 'Break-Fix vs Managed IT', url: 'https://turnkey.pro/the-real-difference-between-break-fix-it-and-managed-it-services/' },
    ],
  },
  {
    title: 'Modern Eastern Fashion',
    icon: 'ShoppingBag',
    type: 'on-page',
    links: [
      { id: 'op56', label: 'Shalwar Kameez Body Match', url: 'https://docs.google.com/document/d/1IweDq2JEFyMgvcum-QTWrTuYiz4fPteGix694zq3wac/edit?usp=sharing' },
      { id: 'op57', label: 'Dupatta Styling Guide', url: 'https://docs.google.com/document/d/1J6tML1fH4ARjZ009-Qt5Uen2dps38y_zmsue8APBE_s/edit?usp=sharing' },
      { id: 'op58', label: '2025 Shalwar Kameez Trends', url: 'https://docs.google.com/document/d/1LSaQ3UlY6GAL4PO3ydn8hop03d6oIMdzRtqj5n9jXn8/edit?usp=sharing' },
      { id: 'op59', label: 'Hand Embroidery Trends', url: 'https://docs.google.com/document/d/1nqwJWr5tFFZHORr2EKkfuSH6YSIoqXosw_2Yfc7fSa0/edit?tab=t.0#heading=h.q5q0baodvnqr' },
      { id: 'op60', label: 'Lehenga Design Selection', url: 'https://docs.google.com/document/d/1NUZK9nUsA8zf7zgvV7WL_JHErz80Z4i6lwVC9chYme0/edit?tab=t.0' },
      { id: 'op61', label: 'Sherwani Color Choice', url: 'https://docs.google.com/document/d/1z_NmriHhCL1yWCxR1d8e9ce5eCuPNfCle-HVVuUMtlQ/edit?tab=t.0' },
      { id: 'op62', label: 'Historic Bridal Fabrics', url: 'https://docs.google.com/document/d/1MUJNAMzZ3d50uuNr9vRXormWKo02by9TBytqZ_5lj3k/edit?tab=t.0' },
      { id: 'op63', label: 'Men Kurta Pajama Styles', url: 'https://docs.google.com/document/d/1DGwCoBOXEebDSk8bnxQ58HsZcL2UJHykGnDjSR4TjNg/edit?tab=t.0' },
      { id: 'op64', label: 'Wedding Anarkali Selection', url: 'https://docs.google.com/document/d/1qAkzovhKJX-x0Aq048atLjMz7otUqdZcLXYzC9n5bRU/edit?tab=t.0#heading=h.qqcq36stqrq6' },
      { id: 'op65', label: 'Saree Mehendi Drape', url: 'https://docs.google.com/document/d/12aNQd8AXBpfgLLmSFcSpVs08LFS7J4eUW1LfakDDeBc/edit?tab=t.0' },
      { id: 'op66', label: 'Bridal Lehenga Body Guide', url: 'https://docs.google.com/document/d/1s8DzfA8DO8K5xWaQJKblthqqZJe7KgC5_T1ElbLK1Zc/edit?tab=t.0' },
      { id: 'op67', label: '2025 Bridal Colors', url: 'https://docs.google.com/document/d/1nLMImegvepZ6bjw8pMVobYVpQGhp2j-zmp9Y8DBozAs/edit?tab=t.0' },
      { id: 'op68', label: 'Top Bridal Fabrics 2025', url: 'https://docs.google.com/document/d/1WLhaxWr5-YeGsDVxtUi4nY_uMJmYRehSxhBvDk3rmks/edit?usp=sharing' },
      { id: 'op69', label: 'Anarkali Occasion Guide', url: 'https://docs.google.com/document/d/16Q9af7iOcAPE4d2LjUz7N_x66ClnNOr4rLp7EFjYvQ0/edit?tab=t.0#heading=h.k76c6nnd59oe' },
      { id: 'op70', label: 'Saree Color Combinations', url: 'https://docs.google.com/document/d/1cRRmglbq2jIpcPUoidSu53pywDteucsPagJvzPbP-PE/edit?usp=sharing' },
      { id: 'op71', label: 'Designer Lehenga Match', url: 'https://docs.google.com/document/d/1qcbQVIkgd1qaMstjYlil5HaoCa1-HcYVf-RbGIasLeM/edit?usp=sharing' },
      { id: 'op72', label: 'Cotton Kurta Set Fabrics', url: 'https://docs.google.com/document/d/1-mg2GcOiI0ZgY-GK120gvSE0AwnAzuo5MizDgbo8Uvo/edit?usp=sharing' },
      { id: 'op73', label: 'Groom Wear Mistakes', url: 'https://docs.google.com/document/d/1Z8ixtZwWdukOw7eOMj-PHWrj7aCuKfSMQ2LiAR2oX1I/edit?usp=sharing' },
    ],
  },
  {
    title: 'Lifestyle & Relationships',
    icon: 'Heart',
    type: 'on-page',
    links: [
      { id: 'op74', label: 'Psychology of Providers', url: 'https://www.artoffemme.io/post/the-psychology-of-a-provider-vs-the-performance-of-a-pretender' },
      { id: 'op75', label: 'Attract Generosity', url: 'https://www.artoffemme.io/post/how-to-attract-a-generous-man-without-asking' },
      { id: 'op76', label: 'Spotting Low Effort', url: 'https://www.artoffemme.io/post/breadcrumbs-aren-t-gourmet-how-to-spot-low-effort-before-it-wastes-your-time' },
      { id: 'op77', label: 'High-Value Spaces', url: 'https://www.artoffemme.io/post/how-to-walk-into-high-value-spaces-as-you-belong-there' },
      { id: 'op78', label: 'Dating High-Value Men', url: 'https://www.artoffemme.io/post/the-unspoken-code-of-dating-men-with-money-and-keeping-their-respect' },
    ],
  },
  {
    title: 'Yoga & Mindfulness',
    icon: 'Feather',
    type: 'on-page',
    links: [
      { id: 'op79', label: '200hr YTT Duration', url: 'https://www.inletyoga.com/how-long-200-hour-yoga-teacher-training-take/' },
      { id: 'op80', label: '200hr YTT Cost Analysis', url: 'https://www.inletyoga.com/how-much-does-a-200-hour-teacher-training-yoga-cost/' },
      { id: 'op81', label: 'Advanced Training Creativity', url: 'https://www.inletyoga.com/7-ways-advanced-yoga-teacher-training-reboots-creativity/' },
      { id: 'op82', label: 'NJ Instructor Certification', url: 'https://www.inletyoga.com/yoga-instructor-certification-nj/' },
      { id: 'op83', label: 'Secrets to YTT Success', url: 'https://www.inletyoga.com/secrets-to-success-in-yoga-teacher-training-nj-programs/' },
      { id: 'op84', label: 'Comprehensive NJ YTT Guide', url: 'https://www.inletyoga.com/everything-about-yoga-teacher-training-nj-you-should-know/' },
      { id: 'op85', label: '300hr YTT Life Benefits', url: 'https://www.inletyoga.com/7-life-changing-benefits-of-300-hour-yoga-teacher-training/' },
      { id: 'op86', label: 'Growth Tips for 300hr', url: 'https://www.inletyoga.com/tips-to-grow-during-a-300-hour-in-yoga-teacher-training/' },
      { id: 'op87', label: 'Wellness Pricing Guide', url: 'https://www.inletyoga.com/inlet-yoga-pricing-and-memberships/' },
      { id: 'op88', label: 'Core YTT Learning Path', url: 'https://www.inletyoga.com/what-you-learn-in-yoga-teacher-training-200hr/' },
      { id: 'op89', label: 'Beyond Certification Value', url: 'https://www.inletyoga.com/why-200-hour-yoga-teacher-training-is-more-than-certification/' },
      { id: 'op90', label: 'Emotional Balance in YTT', url: 'https://www.inletyoga.com/200-hour-yoga-teacher-training-emotional-balance/' },
      { id: 'op91', label: 'Beginner Yoga Foundations', url: 'https://www.inletyoga.com/beginner-yoga-class-at-inlet-yoga/' },
      { id: 'op92', label: 'Yoga for Emotional Balance', url: 'https://www.inletyoga.com/can-yoga-classes-for-beginners-help-with-emotional-balance/' },
      { id: 'op93', label: 'Absolute Beginners Guide', url: 'https://www.inletyoga.com/beginner-yoga-classes-guide-from-inlet-yoga/' },
      { id: 'op94', label: '2026 Private Yoga Trends', url: 'https://www.inletyoga.com/people-are-choosing-private-yoga-classes-in-2026/' },
      { id: 'op95', label: 'Value of Private Sessions', url: 'https://www.inletyoga.com/why-private-yoga-class-price-matters/' },
      { id: 'op96', label: 'Manasquan NJ Wellness', url: 'https://www.inletyoga.com/inlet-yoga-manasquan-nj-wellness-guide/' },
      { id: 'op97', label: 'Aerial vs Traditional Yoga', url: 'https://www.inletyoga.com/aerial-yoga-vs-traditional-yoga/' },
      { id: 'op98', label: 'Starting Your Yoga Journey', url: 'https://www.inletyoga.com/beginners-guide-to-yoga-starting-your-journey-with-inlet-yoga/' },
    ],
  },
  {
    title: 'Mental Health & Telehealth',
    icon: 'Stethoscope',
    type: 'on-page',
    links: [
      { id: 'op117', label: 'Mental Health symptoms Guide', url: 'https://section125group.com/understanding-common-mental-health-conditions-and-symptoms' },
      { id: 'op118', label: 'Online Therapy Preparation', url: 'https://section125group.com/preparation-for-first-online-therapy-session' },
      { id: 'op119', label: 'AI in Mental Diagnosis', url: 'https://section125group.com/ai-for-mental-health-diagnosis' },
      { id: 'op120', label: 'Virtual Therapy Privacy', url: 'https://section125group.com/privacy-confidentiality-in-virtual-therapy' },
      { id: 'op121', label: 'Mental Health Retreats', url: 'https://section125group.com/mental-health-retreats-employee-retention' },
      { id: 'op122', label: 'Online Therapy for Teens', url: 'https://section125group.com/online-therapy-for-teens-employee-benefit' },
      { id: 'op123', label: 'QSR Employee Support', url: 'https://section125group.com/mental-health-support-qsr-employees-inperson-vs-online' },
      { id: 'op124', label: 'Self-Care for Franchisees', url: 'https://section125group.com/self-care-for-fast-food-franchise-owners' },
      { id: 'op125', label: 'Building Resilience ROI', url: 'https://section125group.com/building-resilience-emotional-wellbeing-employee-engagement' },
      { id: 'op126', label: 'Insurance for Depression', url: 'https://section125group.com/health-insurance-covers-depression-anxiety-treatment' },
      { id: 'op127', label: 'Home Health Teletherapy', url: 'https://section125group.com/teletherapy-benefits-for-home-health-workers' },
    ],
  },
  {
    title: 'Hypnosis Practice Growth',
    icon: 'Brain',
    type: 'on-page',
    links: [
      { id: 'hp1', label: 'Hypnosis Marketing Automation', url: 'https://hypnobiz-in-a-box.com/post/hypnosis-marketing-automation-focus-on-clients-not-tech' },
      { id: 'hp2', label: 'Effortless Practice Growth', url: 'https://hypnobiz-in-a-box.com/post/effortless-growth-the-best-hypnotherapy-appointment-software' },
      { id: 'hp3', label: 'Reliable Business Calendar', url: 'https://hypnobiz-in-a-box.com/post/boost-client-satisfaction-with-a-reliable-hypnosis-business-calendar' },
      { id: 'hp4', label: '6-Figure Growth Advertising', url: 'https://hypnobiz-in-a-box.com/post/top-hypnosis-advertising-marketing-solutions-for-6-figure-growth' },
      { id: 'hp5', label: 'Client Management Systems', url: 'https://hypnobiz-in-a-box.com/post/top-hypnosis-client-management-system-for-professional-success' },
      { id: 'hp6', label: 'Affordable Marketing Hacks', url: 'https://hypnobiz-in-a-box.com/post/top-hypnotherapist-marketing-solutions-affordable-professional' },
      { id: 'hp7', label: 'Professional Website Builder', url: 'https://hypnobiz-in-a-box.com/post/best-hypnosis-website-builder-for-professional-hypnotherapists' },
      { id: 'hp8', label: 'Hypnosis Income Strategies', url: 'https://hypnobiz-in-a-box.com/post/top-10-proven-strategies-for-hypnosis-business-income-growth' },
      { id: 'hp9', label: 'Sales Funnel Success', url: 'https://hypnobiz-in-a-box.com/post/best-hypnotherapist-sales-funnel-builder-convert-80-of-leads' },
      { id: 'hp10', label: 'Time-Saving Admin Tools', url: 'https://hypnobiz-in-a-box.com/post/top-hypnosis-business-tools-to-save-10-hours-a-week' },
      { id: 'hp11', label: 'Kajabi Alternative Choice', url: 'https://hypnobiz-in-a-box.com/post/hypnobiz-in-a-box-the-best-kajabi-alternative-for-hypnotists' },
      { id: 'hp12', label: 'Market & Attract 30 Clients', url: 'https://hypnobiz-in-a-box.com/post/how-to-market-your-hypnosis-business-and-attract-30-clients-in-30-days' },
      { id: 'hp13', label: 'SEO for Hypnotherapists', url: 'https://hypnobiz-in-a-box.com/post/seo-vs-paid-ads-for-hypnotherapists-best-roi-in-2025' },
      { id: 'hp14', label: 'Rank on Google Maps', url: 'https://hypnobiz-in-a-box.com/post/rank-your-hypnotherapy-practice-on-google-maps' },
      { id: 'hp15', label: 'Reducing Client No-Shows', url: 'https://hypnobiz-in-a-box.com/post/how-crm-for-hypnotists-reduces-client-no-shows-by-50proven-strategies' },
      { id: 'hp16', label: 'AI in Hypnosis Business', url: 'https://hypnobiz-in-a-box.com/post/using-ai-and-crm-tools-in-your-hypnosis-business-plan-for-better-conversions' },
      { id: 'hp17', label: 'Website Design Trends', url: 'https://hypnobiz-in-a-box.com/post/hypnotherapist-website-design-trends-that-help-you-book-more-sessions' },
      { id: 'hp18', label: 'Mobile-Friendly Approach', url: 'https://hypnobiz-in-a-box.com/post/why-a-mobile-friendly-approach-matters-when-you-create-a-hypnotherapy-website' },
      { id: 'hp19', label: 'Missed Calls to Clients', url: 'https://hypnobiz-in-a-box.com/post/how-to-turn-missed-calls-into-clients-with-online-hypnotherapy-services-automations' },
      { id: 'hp20', label: 'Group Session Scheduling', url: 'https://hypnobiz-in-a-box.com/post/the-best-way-to-handle-group-sessions-using-automated-scheduling-for-hypnotherapists' },
    ],
  },
  {
    title: 'Hypnosis Business Strategy',
    icon: 'Target',
    type: 'on-page',
    links: [
      { id: 'hp21', label: 'Professional Growth Coaching', url: 'https://hypnobiz-in-a-box.com/post/hypnotherapist-business-coaching-software-for-professional-growth' },
      { id: 'hp22', label: '2025 Business Calendar', url: 'https://hypnobiz-in-a-box.com/post/create-your-2025-hypnosis-business-calendar-before-its-too-late' },
      { id: 'hp23', label: 'Expert Income Tech', url: 'https://hypnobiz-in-a-box.com/post/expert-technology-for-hypnosis-business-income-growth' },
      { id: 'hp24', label: 'Book 20 Clients Weekly', url: 'https://hypnobiz-in-a-box.com/post/how-to-start-a-hypnosis-business-and-book-20-clients-per-week' },
      { id: 'hp39', label: 'Book 20+ Clients Strategy', url: 'https://hypnobiz-in-a-box.com/post/how-to-start-a-hypnosis-business-and-book-20-plus-clients' },
      { id: 'hp25', label: 'Online Hypnosis No Tech', url: 'https://hypnobiz-in-a-box.com/post/how-to-start-an-online-hypnosis-business-without-tech-skills' },
      { id: 'hp26', label: 'Single Best Plan Element', url: 'https://hypnobiz-in-a-box.com/post/whats-the-single-most-important-element-of-a-hypnosis-business-plan' },
      { id: 'hp27', label: 'Local SEO Authority', url: 'https://hypnobiz-in-a-box.com/post/how-to-attract-local-hypnotherapy-clients-with-seo' },
      { id: 'hp28', label: 'Near Me Search Optimization', url: 'https://hypnobiz-in-a-box.com/post/optimizing-your-hypnotherapy-website-for-near-me-searches' },
      { id: 'hp29', label: 'Attract Clients via Automation', url: 'https://hypnobiz-in-a-box.com/post/how-to-get-hypnotherapy-clients-through-smart-automations' },
      { id: 'hp30', label: 'Why Hypnobiz Fails', url: 'https://hypnobiz-in-a-box.com/post/why-hypnotherapists-often-fail-without-business-software-and-how-to-avoid-it' },
      { id: 'hp31', label: 'AI Transforming Websites', url: 'https://hypnobiz-in-a-box.com/post/how-ai-is-reshaping-the-future-of-hypnosis-websites' },
      { id: 'hp32', label: 'Private Practice Design Hacks', url: 'https://hypnobiz-in-a-box.com/post/private-practice-website-design-hacks-every-hypnotherapist-should-know' },
      { id: 'hp33', label: 'Blog Traffic Boost Secrets', url: 'https://hypnobiz-in-a-box.com/post/why-a-blog-section-can-boost-your-hypnotherapy-private-practice-website-traffic' },
      { id: 'hp34', label: 'Administrative Time Savings', url: 'https://hypnobiz-in-a-box.com/post/how-hypnotherapy-software-online-helps-hypnotherapists-save-time-on-administrative-tasks' },
      { id: 'hp35', label: 'Instant Credibility Psychology', url: 'https://hypnobiz-in-a-box.com/post/the-psychology-behind-hypnosis-sites-that-build-instant-credibility' },
      { id: 'hp36', label: 'App-Based Client Comms', url: 'https://hypnobiz-in-a-box.com/post/how-a-hypnotherapy-appointment-app-improves-client-communication' },
      { id: 'hp37', label: 'Impact of Management Software', url: 'https://hypnobiz-in-a-box.com/post/the-impact-of-client-management-software-for-hypnotherapists-on-client-satisfaction' },
      { id: 'hp38', label: '5 Tech Problems Solved', url: 'https://hypnobiz-in-a-box.com/post/5-common-tech-problems-solved-by-all-in-one-software-for-hypnotherapists' },
    ],
  },
  {
    title: 'Employee Benefits & Tax',
    icon: 'Wallet',
    type: 'on-page',
    links: [
      { id: 'op99', label: 'Health Broker Differences', url: 'https://section125group.com/do-you-know-what-makes-independent-health-insurance-brokers-different/' },
      { id: 'op100', label: 'FSA Pre-Tax Savings', url: 'https://section125group.com/how-to-find-out-what-pre-tax-savings-do-i-have-with-my-fsa' },
      { id: 'op101', label: 'Advanced Tax Saving Tips', url: 'https://section125group.com/exclusive-tax-saving-tips-from-tax-saving-experts-from-tax-return-system/' },
      { id: 'op102', label: 'Top Employee Benefits', url: 'https://section125group.com/how-to-identify-companies-with-best-employee-benefits-before-applying/' },
      { id: 'op103', label: 'Retirement Safety Nets', url: 'https://section125group.com/hospital-indemnity-insurance-can-save-your-retirement/' },
      { id: 'op104', label: 'Section 125 Payroll Tax', url: 'https://section125group.com/payroll-taxes-with-section-125-plans/' },
      { id: 'op105', label: 'Medical Insurance Supplements', url: 'https://section125group.com/protecting-your-family-with-a-medical-insurance-supplement/' },
      { id: 'op106', label: 'DNA Screening Economics', url: 'https://section125group.com/dna-screening-costs-impact/' },
      { id: 'op107', label: 'Cafeteria Plan Structures', url: 'https://section125group.com/section-125-cafeteria-plans/' },
      { id: 'op108', label: 'Insurance Broker Insight', url: 'https://section125group.com/what-is-an-insurance-broker/' },
      { id: 'op114', label: 'FICA Tax Exemptions', url: 'https://section125group.com/maximize-fica-tax-exemption-for-educational-institutions/' },
      { id: 'op115', label: 'Tax Credits for Employers', url: 'https://section125group.com/save-1000-per-employee-with-tax-credits' },
      { id: 'op116', label: 'HSA Tax Reporting Tips', url: 'https://section125group.com/hsa-tax-reporting-tips' },
      { id: 'op128', label: 'FICA Tax Exemption 2025', url: 'https://section125group.com/fica-tax-exemption-changes-2025' },
      { id: 'op129', label: 'Retain Talent with Low Tax', url: 'https://section125group.com/top-strategies-for-retain-talent-with-low-taxes' },
      { id: 'op130', label: 'Digital Benefits Checklist', url: 'https://section125group.com/digital-employee-benefits-checklist' },
      { id: 'op131', label: 'Reducing Financial Stress', url: 'https://section125group.com/reducing-employee-financial-stress' },
    ],
  },
  {
    title: 'Bridal Makeup & Glam',
    icon: 'Sparkles',
    type: 'on-page',
    links: [
      { id: 'op19', label: 'Tampa vs Miami Trends', url: 'https://citylightsmakeup.com/post/tampa-vs-miami-bridal-makeup-trends-2025' },
      { id: 'op20', label: 'Airbrush Makeup Benefits', url: 'https://citylightsmakeup.com/post/benefits-of-airbrush-bridal-makeup-for-your-wedding-day' },
      { id: 'op21', label: 'Top 10 Hiring Questions', url: 'https://citylightsmakeup.com/post/top-10-questions-to-ask-before-hiring-a-bridal-makeup-artist' },
      { id: 'op22', label: 'Skin Prep Guide', url: 'https://docs.google.com/document/d/1mlY1nfHov05Gxyrz4aCUqZlm2U36KpH0WDrH8pofGk8/edit?usp=sharing' },
      { id: 'op23', label: 'Red Carpet Glam Secrets', url: 'https://docs.google.com/document/d/1mWK91FuQerWpCwD5PJODFYrLAiFLFnrb1GAtH1ER5Gs/edit?usp=sharing' },
      { id: 'op24', label: 'Chicago Seasonal Looks', url: 'https://docs.google.com/document/d/1h2w1gC_n-ttt5OdYQGtlt1xw_Ycm7Eyi5QDSu2ca4gU/edit?usp=sharing' },
      { id: 'op25', label: 'Climate & Makeup Choices', url: 'https://docs.google.com/document/d/1UYzoR4m7r-ACIqjrqp96O2fnhLJG7IzewUGJhd1ADIY/edit?usp=sharing' },
    ],
  },

  // --- OFF-PAGE GUEST POSTS (Electrical & Real Estate) ---
  {
    title: 'Electrical Engineering',
    icon: 'Zap',
    type: 'off-page',
    links: [
      { id: 'gp1', label: 'Residential Contractors Guide', url: 'https://medium.com/@msnider.carpediem/residential-electrical-contractors-expert-home-electrical-services-5eed92de6ca4' },
      { id: 'gp2', label: 'Advanced Power Upgrades', url: 'https://medium.com/@msnider.carpediem/expert-electrical-upgrades-advanced-power-services-e5204c101846' },
      { id: 'gp3', label: 'EV Charger Installation', url: 'https://medium.com/@msnider.carpediem/residential-electrical-contractors-home-ev-charger-installation-c70d086ffb89' },
      { id: 'gp4', label: 'Reliable Power Solutions', url: 'https://medium.com/@msnider.carpediem/reliable-power-solutions-with-advanced-electrical-services-85285db13d11' },
      { id: 'gp5', label: 'Smart Home Setup', url: 'https://buketio.net/smart-home-electrical-setup-efficient-electrician-solution/' },
      { id: 'gp30', label: 'Salem Electrician Services', url: 'https://gamesbad.com/expert-salem-electrician-for-reliable-electrical-services/' },
      { id: 'gp31', label: 'Advanced Systems Guide', url: 'https://safetyhomeservices.blogspot.com/2024/11/advanced-electrical-systems-home.html' },
    ],
  },
  {
    title: 'Solar & Renewables',
    icon: 'Sun',
    type: 'off-page',
    links: [
      { id: 'gp7', label: 'Residential Solar Solutions', url: 'https://medium.com/@msnider.carpediem/salem-electrician-top-residential-solar-solutions-for-homes-449ea0ac42f3' },
      { id: 'gp8', label: 'Energy Efficiency Rebates', url: 'https://sportowasilesia.com/discover-electrification-rebates-for-enhanced-energy-efficiency/' },
      { id: 'gp32', label: 'Modern Energy Guide', url: 'https://72soldreviews.net/advancements-in-electrical-companies-modern-energy-solutions/' },
    ],
  },
  {
    title: 'Salem Real Estate',
    icon: 'Building2',
    type: 'off-page',
    links: [
      { id: 'gp10', label: 'North Salem Land Sale', url: 'https://www.tumblr.com/forestridgehomes/766586657888763904/explore-land-and-homes-for-sale-in-north-salem' },
      { id: 'gp11', label: 'New Construction Guide', url: 'https://medium.com/@forestridgehomes3/discover-new-construction-homes-in-salem-oregon-4647c7b3fd14' },
      { id: 'gp12', label: 'Prime Land Opportunities', url: 'https://medium.com/@forestridgehomes3/land-for-sale-in-salem-prime-real-estate-opportunities-009728d91362' },
      { id: 'gp13', label: 'Salem Agent Guidance', url: 'https://newsmedialive.com/real-estate-agents-salem-oregon-expert-guidance/' },
      { id: 'gp33', label: 'Market Trends 2025', url: 'https://crunchbasic.com/north-salem-real-estate-market-trends-and-investment-insights' },
    ],
  },
  {
    title: 'Flooring & Interiors',
    icon: 'Layers',
    type: 'off-page',
    links: [
        { id: 'gp24', label: 'Durable Tile & Stone', url: 'https://logcla.com/blogs/495388/Tile-and-stone-flooring-is-durable-stylish-and-long-lasting' },
        { id: 'gp25', label: 'Commercial Carpet Guide', url: 'https://onlinetechlearner.com/best-commercial-carpet-brands-for-high-traffic-flooring-areas/' },
        { id: 'gp26', label: 'Hardwood Floor Installation', url: 'https://technegraph.com/hardwood-floor-installation/' },
        { id: 'gp27', label: 'Waterproof LVP Flooring', url: 'https://xollion.com/waterproof-lvp-flooring/' },
        { id: 'gp28', label: 'Bathroom Tile Guide', url: 'https://www.tumblr.com/oregonfloortrends-oft/782159331784278016/bathroom-tile-installation-a-complete-guide-from' },
        { id: 'gp29', label: 'Nylon Carpet Benefits', url: 'https://relxnn.com/durable-style-with-nylon-carpet-flooring-for-modern-homes/' },
    ],
  },
  {
    title: 'Smart Home Tech',
    icon: 'Cpu',
    type: 'off-page',
    links: [
      { id: 'gp15', label: 'Smarter Energy Solutions', url: 'https://seolistinghub.com/post/in-house-electric-smarter-energy-solutions-for-modern-homes/' },
      { id: 'gp16', label: 'Installation Best Practices', url: 'https://medium.com/@msnider.carpediem/smart-home-electrical-installation-best-electrical-contractor-a7e849233d0d' },
      { id: 'gp17', label: 'Future of Living Guide', url: 'https://findus.locastify.com/smart-home-electricity-the-future-of-efficient-living/' },
    ],
  },
  {
    title: 'Electrical Safety',
    icon: 'ShieldCheck',
    type: 'off-page',
    links: [
      { id: 'gp18', label: 'Safety & Efficiency Upgrades', url: 'https://medium.com/@msnider.carpediem/ensuring-safety-efficiency-with-electrical-upgrades-22478306f8f1' },
      { id: 'gp19', label: 'Whole Home Surge Protection', url: 'https://sparkarticles.com/best-surge-protection-for-home-salem-a-complete-guide-to-whole-home-electrical-safety/' },
    ],
  },

  // --- GMB POSTS ---
  {
    title: 'Google My Business',
    icon: 'MapPin',
    type: 'gmb',
    links: [
      { id: 'gmb1', label: 'SEO Update #1', url: 'https://share.google/wva3RYiiT5CjHuaql' },
      { id: 'gmb2', label: 'Market Visibility #2', url: 'https://share.google/UYh38ukJZgRoJi4Fo' },
      { id: 'gmb3', label: 'Local Reach #3', url: 'https://share.google/eB3eK9q9I8X1Ffjpv' },
      { id: 'gmb4', label: 'Regional Authority #4', url: 'https://share.google/68fYW4KS5qX6k04G7' },
      { id: 'gmb5', label: 'Business Growth #5', url: 'https://share.google/okoanApKmFCktVboA' },
      { id: 'gmb6', label: 'Service Coverage #6', url: 'https://share.google/W4E7N0h1FOV67xCKx' },
      { id: 'gmb7', label: 'Technical SEO Insights #7', url: 'https://share.google/QPjiIUKsVEmzwDPgU' },
      { id: 'gmb8', label: 'Local Optimization #8', url: 'https://share.google/FONYx0HR41gWLwXh8' },
      { id: 'gmb9', label: 'Engagement Strategy #9', url: 'https://share.google/59BqXuc4DR4eBLRvl' },
      { id: 'gmb10', label: 'Content Distribution #10', url: 'https://share.google/yZUF15IGldoRgu4nw' },
    ],
  },

  // --- WEB PAGES ---
  {
    title: 'Web Page Strategy',
    icon: 'FileText',
    type: 'web-pages',
    links: [
      { id: 'wp1', label: 'Home Page Content', url: 'https://docs.google.com/document/d/1cAQpt9zWIO85iMVjQQFl_hMzFyaA32yoPwjmmohNqRU/edit?usp=sharing' },
      { id: 'wp2', label: 'Mens TRT Service', url: 'https://docs.google.com/document/d/1bQEN6Kbm_qtzyEw3MltlpmiQOEuAx8nKDzPNLqPBWlo/edit?usp=sharing' },
      { id: 'wp3', label: 'Women Hormones HRT', url: 'https://docs.google.com/document/d/1dJYDzuvceflqVkNHMwlxhrsDTrcOUCwE0qqkIfVhUMc/edit?usp=sharing' },
      { id: 'wp4', label: 'Peptide Therapy (1)', url: 'https://docs.google.com/document/d/1bAU18zcTBNn0pFx7tE-fm6Tsi-RpiabMDcQFKjXEhFc/edit?usp=sharing' },
      { id: 'wp5', label: 'Thyroid Treatment', url: 'https://docs.google.com/document/d/1TnMWsgMmT-YKbemjSGdhmgRppuqGUhn9Ub5BCAAGM84/edit?usp=sharing' },
      { id: 'wp6', label: 'EMSculpt NEO', url: 'https://docs.google.com/document/d/1FtYe0EmUb9-6W6fGP9OewKqPIPbDrf0CJJBm41HDOmc/edit?usp=sharing' },
      { id: 'wp7', label: 'Weight Loss Program', url: 'https://docs.google.com/document/d/1TCaCh1orTfNlv_EprEyrYNeaQnku34Ym5gAP9rJvLSA/edit?usp=sharing' },
      { id: 'wp8', label: 'For Men Health', url: 'https://docs.google.com/document/d/1Y8kTT2O5bfENumH8D1MSOXjzK4Tnh71A5nQCDhEuU6c/edit?usp=sharing' },
      { id: 'wp9', label: 'For Women Health', url: 'https://docs.google.com/document/d/1G781MC42gj45mk0sC3jf9W14RIft43PFo6eOL4uDgus/edit?usp=sharing' },
      { id: 'wp10', label: 'Weight Loss Journey', url: 'https://docs.google.com/document/d/1XmdgjlhcGmm-0u6MdGJnNiF3_33EAlw15hc_2eucBog/edit?usp=sharing' },
      { id: 'wp11', label: 'IV Therapy Strategy', url: 'https://docs.google.com/document/d/1Q0zAvUKeQAsukK6KXMSXgZTtSfzs6xWVwRn9_9f09zg/edit?usp=sharing' },
      { id: 'wp12', label: 'Peptide Therapy (2)', url: 'https://docs.google.com/document/d/1L766MTbgr8XJ4GHizYovkZQkPlBsbsG145AfNNR5n7U/edit?usp=sharing' },
      { id: 'wp13', label: 'Body Contouring', url: 'https://docs.google.com/document/d/1zVbBB56t5ThOWDHaESoNnophelWZdwuUoxB1gDnfHH8/edit?usp=sharing' },
      { id: 'wp14', label: 'Transformations', url: 'https://docs.google.com/document/d/19pZvpfkm-SiDjxlufW6ESJ3O1vRdc7C-9B5M6grwi1U/edit?usp=sharing' },
      { id: 'wp15', label: 'IV Nutrition Therapy', url: 'https://docs.google.com/document/d/11S5Uk-qYi4KGT3uIGawUEwFlDRKEP8ro-lBxaMfS5gw/edit?usp=sharing' },
      { id: 'wp16', label: 'B12 Injections', url: 'https://docs.google.com/document/d/1-bhTkZ7aLNPuwB1uFJnlf4zj-gAVhOVjIZRH5Pf-jMY/edit?usp=sharing' },
      { id: 'wp17', label: 'NUVI Fitness', url: 'https://docs.google.com/document/d/1TVE8Hg_WwaazyGnmZg7St6yY0QsWZZ8O_U_oqoLIrLc/edit?usp=sharing' },
      { id: 'wp18', label: 'Contact Us Page', url: 'https://docs.google.com/document/d/17qr_m6WRy1m82vtL0YQqoKjDEO-or8Wgddk5Y8-gxEI/edit?usp=sharing' },
      { id: 'wp19', label: 'Home/Services Strategy', url: 'https://docs.google.com/document/d/13eA8fXvLhTRk3o6g0AjVb3RUa8ELPBl-UJOfI8N90QM/edit?tab=t.0' },
      { id: 'wp20', label: 'Contact Strategy', url: 'https://docs.google.com/document/d/18BX85_cIvLyq31e6TQ18YUAZxLseHYUt0Mxk4S_fL8E/edit?usp=sharing' },
      { id: 'wp21', label: 'Career Strategy', url: 'https://docs.google.com/document/d/1zD7HFT921-O5eLku11HuJXIQ_yrBq_0pTADOKu66EuY/edit?usp=sharing' },
      { id: 'wp22', label: 'Homepage Strategy', url: 'https://docs.google.com/document/d/1chK81Nbe3mfRenbuDhPIqCXfMywiOe0xo6ie6vsaRFU/edit?usp=sharing' },
      { id: 'wp23', label: 'Detailed Services', url: 'https://docs.google.com/document/d/1s92O5oAIkYSPwCjyLvQFbNfssrW1O_swW94sRDn36U4/edit?tab=t.0#heading=h.wavpyl3mhqnc' },
    ],
  },

  // Niche placeholders
  { title: 'SaaS Copywriting', icon: 'FileJson', type: 'on-page', links: [] },
  { title: 'AI & Automation', icon: 'Bot', type: 'on-page', links: [] },
  { title: 'Fintech Market', icon: 'TrendingUp', type: 'on-page', links: [] },
  { title: 'Cybersecurity', icon: 'Shield', type: 'on-page', links: [] },
  { title: 'Cloud Computing', icon: 'Cloud', type: 'on-page', links: [] },
  { title: 'Cryptocurrency', icon: 'Bitcoin', type: 'on-page', links: [] },
  { title: 'Personal Finance', icon: 'Wallet', type: 'on-page', links: [] },
  { title: 'Accounting Firms', icon: 'Calculator', type: 'on-page', links: [] },
  { title: 'Tax Consultants', icon: 'FileText', type: 'on-page', links: [] },
  { title: 'Fitness Brands', icon: 'Dumbbell', type: 'on-page', links: [] },
  { title: 'Mental Health', icon: 'Brain', type: 'on-page', links: [] },
  { title: 'Telehealth', icon: 'Stethoscope', type: 'on-page', links: [] },
  { title: 'Dental Clinics', icon: 'Smile', type: 'on-page', links: [] },
  { title: 'Luxury Fashion', icon: 'ShoppingBag', type: 'on-page', links: [] },
  { title: 'Online Courses', icon: 'Layers', type: 'on-page', links: [] },
  { title: 'Career Coaching', icon: 'Target', type: 'on-page', links: [] },
  { title: 'Amazon Brands', icon: 'Package', type: 'on-page', links: [] },
  { title: 'SEO Agencies', icon: 'Search', type: 'on-page', links: [] },
  { title: 'PPC Agencies', icon: 'MousePointerClick', type: 'on-page', links: [] },
  { title: 'Social Media', icon: 'Share2', type: 'on-page', links: [] },
  { title: 'Law & Consulting', icon: 'Scale', type: 'on-page', links: [] },
  { title: 'YouTube Strategy', icon: 'Youtube', type: 'on-page', links: [] },
  { title: 'DTC Brands', icon: 'ShoppingBasket', type: 'on-page', links: [] },
  { title: 'Investment Platforms', icon: 'TrendingUp', type: 'on-page', links: [] },
  { title: 'CRM Software', icon: 'Users', type: 'on-page', links: [] },
  { title: 'Web Development', icon: 'Code2', type: 'on-page', links: [] },
  { title: 'Nutrition Brands', icon: 'Apple', type: 'on-page', links: [] },
  { title: 'Supplement Companies', icon: 'Zap', type: 'on-page', links: [] },
  { title: 'Cosmetic Surgery', icon: 'Sparkles', type: 'on-page', links: [] },
  { title: 'Skincare Brands', icon: 'Droplets', type: 'on-page', links: [] },
  { title: 'Haircare Products', icon: 'Wind', type: 'on-page', links: [] },
  { title: 'Jewelry Brands', icon: 'Gem', type: 'on-page', links: [] },
  { title: 'Business Coaching', icon: 'Briefcase', type: 'on-page', links: [] },
  { title: 'Language Learning', icon: 'Languages', type: 'on-page', links: [] },
  { title: 'Shopify Stores', icon: 'Store', type: 'on-page', links: [] },
  { title: 'Print-on-Demand', icon: 'Printer', type: 'on-page', links: [] },
  { title: 'Subscription Box', icon: 'CalendarDays', type: 'on-page', links: [] },
  { title: 'Branding Agencies', icon: 'PenTool', type: 'on-page', links: [] },
  { title: 'Video Production', icon: 'Video', type: 'on-page', links: [] },
  { title: 'Consulting Firms', icon: 'MessagesSquare', type: 'on-page', links: [] },
];
